added read_cam.py
sdk2k01/Gestures_I3D pull request #1
Opened 2022-06-19 14:26 UTC by Noob169

2022-06-19 15:17 UTC, soumyadeepkun requested changes
Incorporate the suggested changes, and use [type annotations](https://docs.python.org/3/library/typing.html) for specifying return-types of functions.

2022-06-19 15:17 UTC, soumyadeepkun commented on src/models/read_cam.py
> +bg = None
Use capital letters for global variables.

Ex: 
```python
BG = None
```

2022-06-19 15:17 UTC, soumyadeepkun commented on src/models/read_cam.py
> +cv2.destroyAllWindows()
keep these lines under indent of function for `"__main__"`

2022-06-19 15:21 UTC, soumyadeepkun commented
Also, update `requirements.txt` to reflect list of required non-standard libraries and dependencies. 
Use `pipreqs` or any other appropriate package to update the list.

2022-06-23 06:45 UTC, Noob169 commented
It will be difficult to specify type-annotations since I genuinely have no idea what is the type of objects that are being used by (some) functions. 

As for the other requested changes, I'll see what I can do.

2022-06-23 06:55 UTC, merged